export const COMPONENT0_COUNTER_PLUS = 0;
export const COMPONENT0_STAY_PLUS = 1;
export const COMPONENT0_STAY_START = 2;
export const COMPONENT0_STAY_END = 3;
export const COMPONENT1_COUNTER_PLUS = 4;
export const COMPONENT2_COUNTER_PLUS = 5;